telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 372, in process_update
    handler.handle_update(update, self, check, context)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/handler.py", line 120, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 20, in greet_user
    update.message.replay_text(text)
AttributeError: 'Message' object has no attribute 'replay_text'
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 372, in process_update
    handler.handle_update(update, self, check, context)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/handler.py", line 120, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 15, in greet_user
    update.message.replay_text(text)
AttributeError: 'Message' object has no attribute 'replay_text'
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 372, in process_update
    handler.handle_update(update, self, check, context)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/handler.py", line 120, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 15, in greet_user
    update.message.replay_text(text)
AttributeError: 'Message' object has no attribute 'replay_text'
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 372, in process_update
    handler.handle_update(update, self, check, context)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/handler.py", line 120, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 15, in greet_user
    update.message.replay_text(text)
AttributeError: 'Message' object has no attribute 'replay_text'
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 372, in process_update
    handler.handle_update(update, self, check, context)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/handler.py", line 120, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 15, in greet_user
    update.message.replay_text(text)
AttributeError: 'Message' object has no attribute 'replay_text'
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
